name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: doctolib-appointment-finder

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract version
      id: pkg
      run: echo ::set-output name=version::$(node -p "require('./package.json').version")

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.pkg.outputs.version }}

    - name: Get commit messages
      id: commit-messages
      run: |
        echo 'COMMIT_MESSAGES<<EOF' >> $GITHUB_ENV
        git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h - %s" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Create a new GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.pkg.outputs.version }}
        release_name: Release v${{ steps.pkg.outputs.version }}
        body: ${{ env.COMMIT_MESSAGES }}
        draft: false
        prerelease: false
