name: Check Doctolib

on:
  schedule:
    - cron: "*/15 * * * *"  # toutes les 15 minutes
  workflow_dispatch: # permet de le lancer manuellement

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PRACTITIONER_ID: "123456"
        run: python main.py
